name: URL Shortener CI

# Trigger the workflow on Pull Requests to develop or main branches
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UrlShortener.Tests # Base directory for .NET commands
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x # Target .NET version

      - name: Restore NuGet Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore # Skip restore as it was done in the previous step

      - name: Execute Unit Tests
        run: dotnet test --no-build --verbosity normal # Run tests without rebuilding