server {
    listen 80;

    # Serve static frontend files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Standard SPA fallback: if file not found, serve index.html
        try_files $uri $uri/ /index.html;
    }

}